brave/go-sync

- README.md
Fix https://github.com/brave/go-sync/issues/6
> Fix protobuf compiler installation dead link in README.md

- datastore/sync_entity.go
- datastore/sync_entity_test.go
Fix https://github.com/brave/go-sync/issues/4
> Delete tag item when the matching sync item is being soft-deleted.

- Dockerfile
- Makefile
- docker-compose.yml
- server/server.go
Fix https://github.com/brave/go-sync/issues/14
The response looks as below:
```
{"build_time":"1591392251","commit":"670b2bf","version":"v0.1.0-7-g670b2bf5-dirty"}
```
> Add health-check endpoint

- command/command.go
Fix https://github.com/brave/go-sync/issues/19
> Return error message to clients in ClientToServerResponse and EntryResponse

- command/command.go
- command/command_test.go
It is possible that update entries could be committed along with a newly created parent, in this case, we should replace the parent ID in the update entries too.
Fix #34
> Replace parent ID for update entries too

- command/command.go
Due to eventually read consistency, it is possible when we read updates from
dynamoDB, those server created unique entities including nigori root folder
are not returned. Nigori root folder is essential for client to properly
initializing the sync engine with nigori type, so we return error in this case
and let client retry if they cannot get it in their first NEW_CLIENT GetUpdates
request.
Fix https://github.com/brave/brave-browser/issues/10474
> Let client retry when nigori root entity is not returned for NEW_CLIENT GetUpdates

- command/command.go
- command/command_test.go
Include PRs: 
#36: Let client retry when nigori root entity is not returned for NEW_CLIENT GetUpdates
> Release 06/29/2020

- command/command.go
Include PRs:
#39: Set polling interval to 60s and sessions commit delay to 30s
> Release 07/16/2020

- Makefile
- cache/instrumented_redis.go
- server/server.go
> Instrument redis calls

- command/command.go
- command/command_test.go
- datastore/datastore.go
- datastore/instrumented_datastore.go
- datastore/sync_entity.go
- datastore/sync_entity_test.go
Fix https://github.com/brave/go-sync/issues/69
> Use mtime as version

- command/command.go
Fix #84 
I manually tested it on sync-dev, will get below result if exceed the limit.
> Allow adding only up to 20 active devices for one account

- auth/auth.go
- command/command.go
> Release 12/02/2021

- cache/cache.go
- command/command.go
> Release 12/07/2021

- command/command.go
Fixes https://github.com/brave/go-sync/issues/95
> Bump max active device limit to 50

- docker-compose.yml
> Update redis image to ubuntu/redis:latest

- controller/controller.go
https://github.com/brave/go-sync/issues/106
> Don't try to process failed request

- server/server.go
When a spot interruption occurs, processes receive a SIGTERM to allow for a graceful shutdown before the container is terminated.
Currently, this would result in the process exiting immediately, while it is still being considered healthy by the load balancer.
This change disables the health check endpoint upon receiving a SIGTERM signal, which allows for deregistration from the load balancer while still allowing the process to handle other requests.
> Handle SIGTERM gracefully

- README.md
This was the missing part for me in terms of running my own local server.
> Mention the --sync-url client flag

- datastore/dynamo.go
This PR introduces a custom HTTP Client with adjusted settings to improve connection reuse / reliability for DynamoDB connections.
> Implement custom http transport

- cache/cache.go
- cache/cache_test.go
- cache/instrumented_redis.go
- cache/redis.go
- command/command.go
- command/command_test.go
- datastore/item_count.go
- datastore/item_count_test.go
- docker-compose.yml
Resolves https://github.com/brave/go-sync/issues/256
> Store interim counts in Redis

- command/command.go
will deploy tomorrow if db i/o + table size continues to be under control
> Increase quotas
